name: REC-ESBM
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  name: goodreads-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - beautifulsoup4=4.13.5
  - matplotlib=3.10.5
  - numba=0.61.2
  - numpy=2.2.5
  - pandas=2.3.1
  - requests=2.32.5
  - scipy=1.16.0
  - seaborn=0.13.2
  - scikit-learn=1.7.1
  - pyyaml=6.0.2