general_params: &general_params
  num_users: 100
  num_items: 100
  bar_h_users: 2
  bar_h_items: 2
  n_iters: 200
  burn_in: 50
  thinning: 2
  k: 10
  seed: 1

params_baseline: &baseline
  cov_users: null
  cov_items: null
  prior_a: 1
  prior_b: 1
  seed: 42
  bar_h_users: 8
  bar_h_items: 5
  scheme_param: 1
  gamma: 0.1
  epsilon: !!float 1e-30
  sigma: 0.7
  alpha_c: [1.5, 1.5, 1.5, 1.5]
  user_clustering: random
  item_clustering: random

params_variants:
  dp:
    <<: *baseline
    degree_param_users: 10
    degree_param_items: 10
    scheme_param: 2
    scheme_type: DP

  py:
    <<: *baseline
    degree_param_users: 10
    degree_param_items: 10
    scheme_param: 2
    sigma: 0.1
    scheme_type: PY

  gn:
    <<: *baseline
    degree_param_users: 10
    degree_param_items: 10
    gamma: 0.55
    scheme_type: GN

  dp_cov:
    <<: *baseline
    degree_param_users: 2
    degree_param_items: 2
    scheme_param: 2
    scheme_type: DP

  py_cov:
    <<: *baseline
    degree_param_users: 2
    degree_param_items: 2
    scheme_param: 1.3
    sigma: 0.1
    scheme_type: PY

  gn_cov:
    <<: *baseline
    degree_param_users: 2
    degree_param_items: 2
    gamma: 0.55
    scheme_type: GN